name = "your-api-name"
main = "src/index.js"
compatibility_date = "2023-12-01"

# Worker configuration
usage_model = "bundled"  # Options: "bundled" or "unbound"

# Environment settings
[env.production]
# Add environment-specific settings here if needed

# Variables
[vars]
# Add your variables here if needed
# EXAMPLE_VAR = "example-value"

# KV Namespaces (if needed)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-namespace-id"

# Secrets (defined via wrangler CLI, not here)
# Run: wrangler secret put SECRET_NAME

# Routes (if you're adding to an existing zone)
# [routes]
# pattern = "example.com/api/*"
# zone_id = "your-zone-id"  # Only needed if not using a *.workers.dev subdomain